### ISSUE TITLE
Server returned HTTP response code: 403

### ISSUE THREAD

**Issue by Smokietr** [yonggeun/coronavirus-live-update#3]
When I try to run the application I get an error like this.

**Comment by yonggeun** [comment]
hi Smokietr,  can I have the output from the console of Processing IDE? either as a screenshot or you can simply copy and paste them it here.  

![image](https://user-images.githubusercontent.com/7887740/92461553-01a71080-f1fc-11ea-815b-edd44cccdf37.png)

Plz, se the clipboard button at the top right side of the console pannel.

**Comment by Smokietr** [comment]
```
java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.worldometers.info/coronavirus/
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at processing.core.PApplet.createInputRaw(PApplet.java:7159)
	at processing.core.PApplet.createInput(PApplet.java:7105)
	at processing.core.PApplet.loadStrings(PApplet.java:7568)
	at covid19live$Loader.getUpdatedOn(covid19live.java:573)
	at covid19live$Loader.load(covid19live.java:383)
	at covid19live.setup(covid19live.java:112)
	at processing.core.PApplet.handleDraw(PApplet.java:2432)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.worldometers.info/coronavirus/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at processing.core.PApplet.createInputRaw(PApplet.java:7152)
	... 8 more
The file "http://www.worldometers.info/coronavirus/" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
> http://www.worldometers.info/coronavirus/ is missing or inaccessible 2020 09-07 03:48:56
> EOF - in training mode 
The font "font/Roboto Slab 700.ttf" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
The font "font/Roboto Condensed 700.ttf" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
The font "font/Roboto Condensed regular.ttf" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
ArrayIndexOutOfBoundsException: Row 0 does not exist.
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help ? Troubleshooting.

```

Hi bro. This is the error I get.

**Comment by Smokietr** [comment]
@yonggeun Can you help me ?
